[package]
name = "simd-exercise"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "pop_count_benchmark"
harness = false

[[bench]]
name = "decode_base64_benchmark"
harness = false
